Development
notification-forge/notif-be pull request #28
Opened 2021-04-17 07:33 UTC by kaiyanghuan

Added Junit Test for templates and templateVersions

2021-04-17 07:41 UTC, cjjavellana requested changes

2021-04-17 07:41 UTC, cjjavellana commented on messaging-service/src/main/kotlin/com/forge/messageservice/repositories/TemplateRepository.kt
> +    fun findAllLikeNameAndInAppCodes(name: String, appCodes: List<String>, pageable: Pageable): Page<Template>
suggest renaming to `findWithNamesLike` since it's using @Query anyway. The `appCode`s need not be part of the method name, it's implicit that `appCode` is required from the parameter list.

Propose switching order of appCodes and names, as `fileNames` are within the context of an `appCode` and when the function is read from left to right, appCode is a larger context than filename

2021-04-17 07:41 UTC, cjjavellana commented on messaging-service/src/test/kotlin/com/forge/messageservice/services/TemplateServiceTest.kt
> +    fun itShouldReturnTemplateWhenCreatingTemplateAndExceptionWhenTemplateNameAndAppCodeAlreadyExist() {
Suggest to break into two separate test case

2021-04-17 07:41 UTC, cjjavellana commented on messaging-service/src/test/kotlin/com/forge/messageservice/services/TemplateServiceTest.kt
> +    fun itShouldReturnTemplateWhenUpdatingTemplateAndExceptionWhenTemplateNameAndAppCodeAlreadyExist() {
Suggest to break into 2 separate test case.

2021-04-17 07:45 UTC, cjjavellana requested changes

2021-04-17 07:45 UTC, cjjavellana commented on messaging-service/src/main/kotlin/com/forge/messageservice/entities/TemplateVersion.kt
> +        return Objects.hash(templateId, settings, body, status)
Is it by design that the template's hash will change as the status is changed? .e.g DRAFT version of a template <> PUBLISHED version even when body remains the same? 

Is templateId required to be hashed? Two templates having the same body but different templateId will result to different hash

2021-04-17 08:00 UTC, kaiyanghuan commented on messaging-service/src/main/kotlin/com/forge/messageservice/entities/TemplateVersion.kt
> +        return Objects.hash(templateId, settings, body, status)
hmmmm... true, that make sense.. If don't hash templateId, means different templateId will unable to have the same setting & body right?

2021-04-17 08:00 UTC, kaiyanghuan commented on messaging-service/src/test/kotlin/com/forge/messageservice/services/TemplateServiceTest.kt
> +    fun itShouldReturnTemplateWhenUpdatingTemplateAndExceptionWhenTemplateNameAndAppCodeAlreadyExist() {
got it

2021-04-17 08:00 UTC, kaiyanghuan commented on messaging-service/src/test/kotlin/com/forge/messageservice/services/TemplateServiceTest.kt
> +    fun itShouldReturnTemplateWhenCreatingTemplateAndExceptionWhenTemplateNameAndAppCodeAlreadyExist() {
got it

2021-04-17 08:01 UTC, kaiyanghuan commented on messaging-service/src/main/kotlin/com/forge/messageservice/repositories/TemplateRepository.kt
> +    fun findAllLikeNameAndInAppCodes(name: String, appCodes: List<String>, pageable: Pageable): Page<Template>
i see.. ok. make sense

2021-04-19 03:21 UTC, cjjavellana approved these changes

2021-04-19 03:21 UTC, merged