PR for ErrorHandling in Image and Template Services
notification-forge/notif-be pull request #54
Opened 2021-05-06 10:04 UTC by vagisanm

PR for ErrorHandling in Image and Template Services

2021-05-08 03:17 UTC, cjjavellana requested changes

2021-05-08 03:17 UTC, cjjavellana commented on messaging-service/src/main/kotlin/com/forge/messageservice/exceptions/PageTemplateException.kt
> +open class PageTemplateException(
@vagisanm PageTemplateException & PageImageException seems similar. Can we combine them into a single `QueryException` instead?

2021-05-08 03:19 UTC, vagisanm commented on messaging-service/src/main/kotlin/com/forge/messageservice/exceptions/PageTemplateException.kt
> +open class PageTemplateException(
Noted Christian will make the change

2021-05-11 05:24 UTC, cjjavellana approved these changes

2021-05-11 05:24 UTC, merged